# **Learning Numpy**

In [5]:
import pandas as pd
import numpy as np

In [8]:
# list the embeded Functions!
print(dir(np))
print(dir(pd))

['False_', 'ScalarType', 'True_', '_CopyMode', '_NoValue', '__NUMPY_SETUP__', '__all__', '__array_api_version__', '__array_namespace_info__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__expired_attributes__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__numpy_submodules__', '__package__', '__path__', '__spec__', '__version__', '_array_api_info', '_core', '_distributor_init', '_expired_attrs_2_0', '_globals', '_int_extended_msg', '_mat', '_msg', '_pyinstaller_hooks_dir', '_pytesttester', '_specific_msg', '_type_info', '_typing', '_utils', 'abs', 'absolute', 'acos', 'acosh', 'add', 'all', 'allclose', 'amax', 'amin', 'angle', 'any', 'append', 'apply_along_axis', 'apply_over_axes', 'arange', 'arccos', 'arccosh', 'arcsin', 'arcsinh', 'arctan', 'arctan2', 'arctanh', 'argmax', 'argmin', 'argpartition', 'argsort', 'argwhere', 'around', 'array', 'array2string', 'array_equal', 'array_equiv', 'array_repr', 'array_split'

In [9]:
print("hello"); print("world")

hello
world


In [10]:
a = np.array(1) # 0D
b = np.array([1,2]) # 1D
c = np.array([[1,2],[3,4]]) # 2D
d = np.array([[[1],[2]],[[3],[5]]]) # 3D

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [11]:
print(d[1,1,-1])

5


## **Performance**

>### **Runtime**

In [1]:
import sys
import time

In [2]:
# add elements in 2 lists
elnums = 40000000
list1 = range(elnums)
list2 = range(elnums)
list_start_t = time.time()
list_res = [(n+m) for n,m in zip(list1,list2)]

print(f"list time = {time.time() - list_start_t}")

# list_res

list time = 5.401474714279175


In [3]:
#same with numpy
arr1 = np.arange(elnums)
arr2 = np.arange(elnums)
array_start_t = time.time()
arr_res = arr1 + arr2
print(f"array time = {time.time() - array_start_t}")

NameError: name 'np' is not defined

>### **Storage**

In [ ]:
elnums = 200
list1 = range(elnums)
print(f"elnums: {elnums} ")
print(f"list item size = {sys.getsizeof(list1[1])}")
print(f"total bytes for a list = {sys.getsizeof(list1[1]) * len(list1)}")

elnums: 200 
list item size = 28
total bytes for a list = 5600


In [ ]:
arr1 = np.arange(elnums)
print(f"elnums: {elnums} ")
print(f"list item size = {sys.getsizeof(list1[1])}")
print(f"total bytes for a list = {arr1.itemsize * len(arr1)}")

elnums: 200 
list item size = 28
total bytes for a list = 1600


## **Array Slicing**

In [7]:
b = np.array([["A","B","C"],["D","E","F"],["G","H","I"]])


In [ ]:
print(b[1,2:])
print(b[1][2:]) # same

['F']
['F']


In [10]:
print(b[1:,1:])

[['E' 'F']
 ['H' 'I']]


## **Data Types And Control Array**

In [12]:
# know the data type of an array using .dtype

a1 = np.array([1,2,3,4])
a2 = np.array([1.1, 2.2, 3.3, 4.4])
a3 = np.array(["abdallah","gasem", "elsayed"])     # dtype get <U standing for Unicode then the no of char of a[0] -> <U8

print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
<U8


In [13]:
# force a type will creatng
a2 = np.array([1,2,3,4] , dtype="f")
a3 = np.array([1,2,3,4] , dtype="float")
a4 = np.array([1,2,3,4] , dtype=float)

a5 = np.array([1.1, 2.2, 3.3, 4.4] , dtype=int)
# a3 = np.array(["abdallah","gasem", "elsayed"], dtype=int)     # ERROR
# a1 = np.array([1,2,3,4] , dtype=f)    # ERROR

print(a2.dtype)
print(a3.dtype)
print(a4.dtype)
print(a5.dtype)


float32
float64
float64
int64


In [55]:
# change the dtype of an existing array
a = np.array([1,2,3,4])
print(a.dtype)

a = a.astype("float")
print(a.dtype)

a = a.astype("f")
print(a.dtype)

int64
float64
float32


In [60]:
a = np.array([0,2,3,4,0])
print(a.dtype)

a =  a.astype("bool")
print(a)
print(a.dtype)

int64
[False  True  True  True False]
bool


## **Arithmetic And Useful Operations**

In [61]:
# Arithmetic Operations
a1 = np.array([10,2,24])
a2 = np.array([1,33,2])

print(a1 + a2)
print(a1 - a2)
print(a1 * a2)
print(a1 / a2)

[11 35 26]
[  9 -31  22]
[10 66 48]
[10.          0.06060606 12.        ]


In [62]:
a3 = np.array([[1,2],[4,5]])
a4 = np.array([[3,7],[9,87]])

print( a3 + a4)
print( a3 - a4)
print( a3 * a4)
print( a3 / a4)

[[ 4  9]
 [13 92]]
[[ -2  -5]
 [ -5 -82]]
[[  3  14]
 [ 36 435]]
[[0.33333333 0.28571429]
 [0.44444444 0.05747126]]


In [63]:
# Min, Max & sum
a5 = np.array([56,78,44,3,54])

print(a5.min())
print(a5.max())
print(a5.sum())


3
78
235


In [ ]:
a6 = np.array([[3,7],[9,87]])
print(a6.min()) # out of all the sub arrays !
print(a6.max()) # out of all the sub arrays !
print(a6.sum())

3
87
106


In [65]:
# ravel: returns a flattend array of 1 dimension with the same data type
a8 = np.array([[3,7],[9,87]])
print(a8)
print(a8.ndim)

a8 = a8.ravel()
print(a8)
print(a8.ndim)

[[ 3  7]
 [ 9 87]]
2
[ 3  7  9 87]
1


## **Array Shape And ReShape**

In [ ]:
# shape attribute return the number of elements in each dim
a = np.array([1,2,3,4])
print(a.shape) 

(4,)


In [67]:
a = np.array([[1,2],[3,4]])
print(a.shape)

(2, 2)


In [68]:
a = np.array([[1,2],[3,4],[5,6]])
print(a.shape)

(3, 2)


In [69]:
a = np.array([[1,2,4],[4,3,4]])
print(a.shape)

(2, 3)


In [70]:
a = np.array([[[1,2],[3,4],[5,6]],[[1,2],[3,4],[5,6]]])
print(a.shape)

(2, 3, 2)


In [72]:
# reshape
a = np.array([1,2,3,4,5,6,7,8,9,10])
a = a.reshape(2,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [74]:
a = np.array([1,2,3,4,5,6,7,8,9,10])
a = a.reshape(2,5,1)
print(a)
print(a.ndim)

[[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]]]
3


In [75]:
a = np.array([[1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6,7,8,9,10]])
a = a.reshape(-1)   # same as using ravel it flatens the array!
print(a)
print(a.ndim)

[ 1  2  3  4  5  6  7  8  9 10  1  2  3  4  5  6  7  8  9 10]
1
