### Q_1: create 2D-array that contain even numbers between 0-18...??

In [2]:
import numpy as np

In [4]:
my_list = [i for i in range(0,18) if i % 2 == 0]
my_array = np.array(my_list)
print(my_array)

[ 0  2  4  6  8 10 12 14 16]


### Q_2: Replace the negative values with 0 in random array that has value in range (-6,6)

In [7]:
rarr = np.arange(-6, 6)
rarr[rarr < 0] = 0
rarr


array([0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 5])

### Q_3 :  How to compute ((A+B)*(-A/2)) ?  where A,B random array

In [9]:
A = np.array([1, 2, 3, 4, 5, 6])
B = np.array([1, 2, 3, 4, 5, 6])

c = ((A + B) * (-A / 2))
c

array([ -1.,  -4.,  -9., -16., -25., -36.])

### Q_4: How to concatenate two arrays horizontally..?

In [ ]:
A = np.array([1, 2, 3, 4, 5, 6])
B = np.array([1, 2, 3, 4, 5, 6])

res = np.concat( (A, B), axis=0 )
res

array([1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6])

#### Q_5: Create a array vector of size 3x3 and sort values in Its columns

In [14]:
vector = np.array([ [3,2,1] , [6,5,4] , [9,8,7] ])

vector.sort()
vector

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])